1) Generate an array of zeroes using inbuilt numpy function.

In [2]:
import numpy as np


In [5]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2) Run the given code and find the dot product of both arrays.

In [6]:
a=np.random.randint(2,10,(3,4))
b=np.random.randint(2,10,(4,3))
print(a)
print(b)

[[5 8 3 7]
 [4 7 2 5]
 [4 2 3 4]]
[[8 5 3]
 [8 8 9]
 [7 6 6]
 [3 7 4]]


In [8]:
a.dot(b)

array([[146, 156, 133],
       [117, 123, 107],
       [ 81,  82,  64]])

In [7]:
np.dot(a,b)

array([[146, 156, 133],
       [117, 123, 107],
       [ 81,  82,  64]])

3)Read the csv file provided using pandas and display the first 5 entries

In [9]:
import pandas as pd

In [10]:
data=pd.read_csv('data.csv')
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

4)Describe the data with all features.

In [12]:
data.shape

(25, 6)

In [14]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB


5)Find the total count of missing values for each feature.

In [17]:
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

6)Display all the unique values from the 'DESCRIPTION’ column.

In [18]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [19]:
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

8)Generate a random sample of 10 rows from the data.

In [20]:
data.sample(10)

OBJECTID                              UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
14        33                Turtle River State Park  ...   0.000378   0.145220
15        34              Lake Sakakawea State Park  ...   0.000357   0.191806
4         25              Grahams Island State Park  ...   0.000469   0.125546
22        44  Turtle Mountain State Recreation Area  ...   0.000345   0.086487
3         24                 Fort Ransom State Park  ...   0.000444   0.128733
7         28             Lewis and Clark State Park  ...   0.000256   0.130420
17        38    Fahlgren Park State Recreation Area  ...   0.000010   0.013294
23        45                 Cross Ranch State Park  ...   0.000274   0.180257
9         30      Fort Mandan State Recreation Area  ...   0.000005   0.009396
5         26                   Icelandic State Park  ...   0.000461   0.166712

[10 rows x 6 columns]

9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [22]:
data['New_feature']=np.random.rand(25,1)
data

OBJECTID  ... New_feature
0         21  ...    0.158063
1         22  ...    0.154299
2         23  ...    0.150248
3         24  ...    0.705787
4         25  ...    0.039647
5         26  ...    0.482328
6         27  ...    0.452805
7         28  ...    0.719578
8         29  ...    0.861274
9         30  ...    0.325081
10        31  ...    0.144007
11        32  ...    0.428710
12        35  ...    0.453282
13        36  ...    0.868532
14        33  ...    0.449152
15        34  ...    0.506228
16        37  ...    0.119428
17        38  ...    0.700427
18        39  ...    0.278319
19        40  ...    0.966531
20        41  ...    0.962481
21        43  ...    0.337077
22        44  ...    0.365574
23        45  ...    0.651129
24        42  ...    0.985642

[25 rows x 7 columns]

10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [25]:
data.replace(data['OBJECTID']==0,data['OBJECTID'].mean(),inplace=True)

In [27]:
(data['OBJECTID']==0).sum()

0

In [28]:
data["OBJECTID"].isnull().sum()

0